spring:
  application:
    name: TravelPackagesAPI
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://35.188.29.161:5432/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update



server:
  port: 8080

api:
  config:
    api2-url: ${}
