spring:
  application:
    name: ReimbursementRequestAPI
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://34.132.27.250:5432/db_reimburse
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

api:
  config:
    api2-url: ${}
