spring:
  application:
    name: TravelPackagesAPI
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://34.71.209.226:5432/travel_packages
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

api:
  config:
    api2-url: ${}
