spring:
  application:
    name: TravelPackagesAPI
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://35.188.29.161:5432/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: token_secret
  expiry:  360000



server:
  port: 8000

api:
  config:
    api2-url: ${}
