---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project2team4-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-deployment
  template:
    metadata:
      labels:
        app: java-deployment
    spec:
      containers:
      - image: project2team4/java:latest
        env:
          - name: REACT_URL
            value: http://34.70.19.242:3030
        imagePullPolicy: Always
        name: javacontainer
        ports: 
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-service
  name: java
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http-app1
      port: 8080
      targetPort: 8080
  selector:
    app: java-deployment







