---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project2team4-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-deployment
  template:
    metadata:
      labels:
        app: java-deployment
    spec:
      containers:
      - image: project2team4/java:latest
        imagePullPolicy: Always
        name: java
        ports: 
        - containerPort: 8000
        livenessProbe:
            httpGet:
              path: /employee/getAllEmployees
              port: 8000
        readinessProbe:
            httpGet:
              path: /employee/getAllEmployees
              port: 8000
      - image: grafana/grafana:latest
        imagePullPolicy: Always
        name: grafana
        ports:
          - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  selector:
    app: java-deployment
    type: NodePort
  ports:
  - port: 8000
    targetPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-ingress-data
  labels:
    name: java-ingress
spec:
  defaultBackend:
    service:
      name: java-service
      port: 
        number: 8000
