---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project2team4-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-deploy
  template:
    metadata:
      labels:
        app: java-deploy
    spec:
      containers:
      - image: project2team4/java:latest
        imagePullPolicy: Always
        name: java-deploy
        ports: 
        - containerPort: 8080
        livenessProbe:
            httpGet:
              path: /employee
              port: 8080
        readinessProbe:
            httpGet:
              path: /employee
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:
  selector:
    app: java-deploy
    type: NodePort
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-ingress-data
  labels:
    name: java-ingress
spec:
  defaultBackend:
    service:
      name: java-service
      port: 
        number: 8080
